# Generated by Django 5.1.4 on 2024-12-16 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(auto_created=True, verbose_name='Дата добавления')),
                ('username', models.CharField(max_length=20, verbose_name='Название книги')),
                ('avtor', models.CharField(max_length=10, verbose_name='Автор')),
                ('genre', models.CharField(max_length=20, verbose_name='Жанр')),
                ('year_of_publication', models.DateField(verbose_name='Дата публикации')),
                ('description', models.TextField(verbose_name='Описание')),
                ('cover', models.ImageField(upload_to='upload/Book/', verbose_name='Обложка книги')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='Имя пользователя')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Почта пользователя')),
            ],
        ),
        migrations.CreateModel(
            name='ReadListBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_name', models.CharField(max_length=20, verbose_name='список книг')),
                ('user', models.CharField(max_length=10, verbose_name='пользователь')),
                ('books', models.ManyToManyField(to='BookInfo.book')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_created=True, verbose_name='Дата создания')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('rating', models.IntegerField(max_length=5, verbose_name='Рейтинг')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookInfo.book')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookInfo.user'),
        ),
    ]
