# Generated by Django 5.1.4 on 2025-01-15 13:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_book', models.CharField(max_length=100, verbose_name='Название книги')),
                ('avtor', models.CharField(max_length=100, verbose_name='Автор')),
                ('genre', models.CharField(max_length=20, verbose_name='Жанр')),
                ('year_of_publication', models.DateField(verbose_name='Дата публикации книги')),
                ('description', models.TextField(verbose_name='Описание')),
                ('cover', models.ImageField(blank=True, default='/upload/Book/Image-not-found.png', upload_to='upload/Book/', verbose_name='Обложка книги')),
                ('date_added', models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Книги',
                'verbose_name_plural': 'Книги',
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='Userdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='Имя пользователя')),
                ('phone', models.IntegerField(blank=True, verbose_name='Номер телефона')),
                ('date_birthday', models.DateField(verbose_name='Дата рождения')),
                ('email', models.EmailField(max_length=255, verbose_name='Почта пользователя')),
                ('avatar', models.ImageField(blank=True, default='/upload/Users/Avatar/avatar_default.png', upload_to='upload/Users/Avatar/', verbose_name='Аватарка')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='ReadListBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_name', models.CharField(max_length=20, verbose_name='список книг')),
                ('user', models.CharField(max_length=10, verbose_name='пользователь')),
                ('books', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookInfo.book')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('creation_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('rating', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookInfo.book', verbose_name='Книга')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='BookInfo.review')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookInfo.userdb', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['creation_at'],
                'unique_together': {('book', 'username')},
            },
        ),
    ]
