# Generated by Django 5.1.6 on 2025-03-03 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookInfo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='year_of_publication',
        ),
    ]
