# Generated by Django 5.1.4 on 2024-12-19 12:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookInfo', '0003_review_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='user',
        ),
        migrations.AlterField(
            model_name='book',
            name='date_added',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='book',
            name='username',
            field=models.CharField(max_length=100, verbose_name='Название книги'),
        ),
    ]
