# Generated by Django 5.1.4 on 2024-12-19 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookInfo', '0004_remove_book_user_alter_book_date_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, unique=True, upload_to='upload/Book/', verbose_name='Обложка книги'),
        ),
    ]
