# Generated by Django 5.1.5 on 2025-01-24 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookInfo', '0004_remove_profile_user_profile_email_profile_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
