# Generated by Django 5.1.6 on 2025-03-03 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookInfo', '0004_alter_favorite_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='genre',
            new_name='genre_name',
        ),
    ]
