# Generated by Django 5.1.5 on 2025-01-24 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookInfo', '0005_remove_profile_first_name_remove_profile_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
    ]
