# Generated by Django 5.1.5 on 2025-01-24 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookInfo', '0006_remove_profile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
