# Generated by Django 5.1.4 on 2024-12-23 13:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookInfo', '0006_alter_book_cover_alter_book_year_of_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='avtor',
            field=models.CharField(max_length=100, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='book',
            name='date_added',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Дата добавления'),
        ),
    ]
