# Generated by Django 5.1.4 on 2025-01-03 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookInfo', '0007_alter_book_avtor_alter_book_date_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='username',
            new_name='name_book',
        ),
    ]
