# Generated by Django 5.1.4 on 2025-01-08 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookInfo', '0008_rename_username_book_name_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, default='upload/BookInfo/image-not-found.png', unique=True, upload_to='upload/Book/', verbose_name='Обложка книги'),
        ),
    ]
