# Generated by Django 5.1.4 on 2025-01-08 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookInfo', '0009_alter_book_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, default='upload/Book/Image-not-found.png', unique=True, upload_to='upload/Book/', verbose_name='Обложка книги'),
        ),
    ]
