# Generated by Django 5.1.5 on 2025-01-31 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookInfo', '0010_alter_favorite_user_alter_favorite_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-creation_at'], 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together=set(),
        ),
    ]
