# Generated by Django 5.1.4 on 2025-01-09 10:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookInfo', '0010_alter_book_cover'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['creation_at']},
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('book', 'username')},
        ),
        migrations.AddField(
            model_name='review',
            name='creation_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='review',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='BookInfo.review'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='upload/Users/Avatar/', verbose_name='Аватарка'),
        ),
        migrations.RemoveField(
            model_name='readlistbook',
            name='books',
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
        migrations.RemoveField(
            model_name='review',
            name='creation_date',
        ),
        migrations.AddField(
            model_name='readlistbook',
            name='books',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='BookInfo.book'),
            preserve_default=False,
        ),
    ]
