# Generated by Django 5.1.4 on 2025-01-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookInfo', '0012_alter_review_options_alter_review_book_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, default='/upload/Book/Image-not-found.png', unique=True, upload_to='upload/Book/', verbose_name='Обложка книги'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='/upload/Users/Avatar/avatar_default.png', upload_to='upload/Users/Avatar/', verbose_name='Аватарка'),
        ),
    ]
