# Generated by Django 5.1.4 on 2025-01-14 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookInfo', '0013_alter_book_cover_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-date_added'], 'verbose_name': 'Книги', 'verbose_name_plural': 'Книги'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, default='/upload/Book/Image-not-found.png', upload_to='upload/Book/', verbose_name='Обложка книги'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='Почта пользователя'),
        ),
    ]
