# Generated by Django 5.1.4 on 2025-01-14 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookInfo', '0014_alter_book_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Userdb',
        ),
    ]
